### ISSUE TITLE
프로젝트 초기 구조 세팅

### ISSUE THREAD

**Issue by minjo-on** [9oormthon2024-T5-SoriSoop/sorisoop-server#1]
### Describe

- **프로젝트를 DDD(Domain-Driven Design) 방식으로 개발하기 위해 초기 구조를 설정합니다.**

- 각 도메인 이름을 디렉터리로 생성하고, 도메인 관련 모든 기능(엔티티, 서비스, 레포지토리, 컨트롤러 등)을 해당 디렉터리 안에 작성합니다.

### 디렉터리 구조
```
src
└── main
    └── java
        └── com.sorisoop.server
            ├── decibel  # 소리 관련 도메인
            │   ├── domain
            │   ├── repository
            │   ├── service
            │   ├── dto
            │   └── controller
            ├── review  # 리뷰 관련 도메인
            │   ├── domain
            │   ├── repository
            │   ├── service
            │   ├── dto
            │   └── controller
            └── common  # 공통 모듈
                ├── domain
                ├── dto
                ├── exception
                └── util
    └── resources
        ├── application.yml
        └── data.sql
```

### 디렉터리 구조 설명
1. **review**: 리뷰를 관리하는 도메인
   - `entity`: 리뷰를 저장하는 엔티티 클래스
   - `repository`: 리뷰를 관리하는 JPA 리포지토리
   - `service`: 리뷰 관련된 비즈니스 로직
   - `controller`: 리뷰 관련 REST API 컨트롤러

2. **noise**: 소음 데이터를 관리하는 도메인
   - `entity`: 소음 데이터를 저장하는 엔티티 클래스
   - `repository`: 소음 데이터를 관리하는 JPA 리포지토리
   - `service`: 소음 데이터와 관련된 비즈니스 로직
   - `controller`: 소음 관련 REST API 컨트롤러

3. **common**: 공통적으로 사용되는 모듈
   - `dto`: 데이터 전송 객체 (Data Transfer Object)
   - `exception`: 예외 처리 관련
   - `util`: 유틸리티 클래스

4. **resources**:
   - `application.yml`: Spring Boot 설정 파일
   - `data.sql`: 초기 데이터를 설정하는 SQL 파일

이 구조를 통해 각 도메인의 책임을 명확히 분리하고, 확장 가능하면서도 유지보수가 용이한 애플리케이션을 설계할 수 있습니다.
 

- **프로젝트 주요 목표**는 공공장소 소음 문제를 해결하기 위해 데이터를 수집하고, 사용자에게 정보를 제공하는 서비스 개발입니다.

- **주요 기능:**
  - i. 특정 위치의 소음 데이터를 수집 및 평균화하여 사용자에게 시각적으로 제공
  - ii. 데이터 필터링 기능 제공
  - iii. QueryDSL을 활용한 복잡한 쿼리 작성

- **필요 기술 스택 및 설정:**
  - Spring Boot 기반 애플리케이션
  - PostgreSQL을 사용한 데이터 저장소
  - QueryDSL을 활용한 필터링 및 쿼리 작성

### Tasks

- [x] 프로젝트 디렉토리 초기화
- [x] Spring Boot, Lombok, Spring Data JPA, QueryDSL, PostgreSQL Driver 등 필요한 의존성 추가 및 설정.
- [x] Entity 및 Repository 초기화
- [x] 소음 데이터를 저장하기 위한 기본 Entity 생성.
- [x] JPA를 활용한 기본 Repository 생성.
- [x] PR 및 Issue 템플릿 추가.

### ETC

1. **DDD(Domain-Driven Design) 방식 채택 이유**  
   - 빠른 협업과 의사소통 -> 도메인을 중심으로 코드를 분리해 팀원 간 의사소통이 원활하고, 역할과 작업 범위가 명확해집니다. 
   - 기능 추가와 수정의 용이성 -> 도메인별로 구조화된 코드는 특정 기능 수정이나 추가 작업 시 다른 부분에 영향을 최소화하여 빠르고 안전하게 작업할 수 있습니다.

2. **디렉터리 구조 설계 이유**  
   - 도메인별 디렉터리 구조는 코드의 가독성을 높이고, 새로운 기능을 추가할 때 해당 도메인에만 집중할 수 있게 합니다.  
   - 공통 모듈(`common`)을 별도로 분리하여 DTO, 예외 처리, 유틸리티 클래스와 같은 재사용 가능한 코드를 한곳에 모아 관리함으로써 중복 코드를 줄입니다.

3. **PostgreSQL 채택 이유**  
   - PostgreSQL은 고급 쿼리 기능과 JSON 데이터를 효과적으로 처리할 수 있는 기능을 제공하여 복잡한 데이터 필터링 및 분석에 적합합니다.  
   - 특히 소음 데이터와 같이 위치 기반의 데이터를 처리할 때 유용한 `PostGIS` 확장을 지원하므로, 위치 데이터를 효율적으로 다룰 수 있습니다.

4. **QueryDSL 사용 이유**  
   - QueryDSL은 JPA를 사용한 복잡한 쿼리 작성을 더 쉽고 안전하게 해줍니다.  
   - 소음 데이터를 특정 조건으로 필터링하거나 평균값을 계산하는 등의 고급 조회 기능을 구현할 때, 코드의 가독성을 유지하면서 동적 쿼리를 작성할 수 있습니다.

5. **DDD와 기술 스택의 조화**  
   - DDD를 기반으로 도메인 모델을 설계하면, PostgreSQL 및 QueryDSL의 강력한 기능과 결합하여 복잡한 비즈니스 로직을 효과적으로 처리할 수 있습니다.  
   - 이러한 설계는 프로젝트의 초기 개발뿐만 아니라, 이후 유지보수와 기능 확장을 고려한 최적의 접근 방식입니다.
