### ISSUE TITLE
[API] 데시벨 측정 데이터 등록

### ISSUE THREAD

**Issue by yohan-kang** [9oormthon2024-T5-SoriSoop/sorisoop-server#11]
### Describe

[Noise 데이터]
소음 데이터 등록  API 추가

### DTO
dto/response/request/NoiseCreateRequest 
```
좌표 : private Point point
평균 데시벨 : int averageDecibel
최대 데시벨 : int maximumDecibel
int minimumDecibel(제외)
평균 데시벨 : int measurementTime
한줄평 : String review
```
### API 명세 
-  HTTP 메서드: POST
-  Endpoint: POST /api/noise

Request Body
```
{
  "id" : 사용자 ID
  "x": 127.001,
  "y": 37.001,
  "averageDecibel": 64,
  "maximumDecibel": 80,
  "measurementTime" : YYYY-MM-DD HH:MM:SS
  "review": " 한줄평"
}
```

Response
```
{
  "id": 1,
  "status": "SUCCESS"
}
```

### Tasks

API 구현
- [x] Noise 데이터  Entity 설계(생략)
- [x] db 저장 Repository 구현
- [x] Service 계층에서 데이터 검증 및 저장 로직 추가
- [x] Controller 계층에서 요청 처리 및 응답 반환 로직 구현.
- [x] 요청 유효성 검사 (위도, 경도, 데시벨 값 범위 확인)
- [x] postman 테스트 

### ETC
create_at 데이터 경우Noise 클래스가 BaseTimeEntity 상속받아서 자동적으로 생성됨 

1 유저 엔티티 수정 
  서비스 로직에서 user도메인의 id를 레포지토리 의존성 주입없이 가져와서 처리하기 위헤서 gpt 참고함 
2  noise 엔티티 수정
  측정시간과  삭제
