### ISSUE TITLE
[API] 위치 기반 공간 검색 

### ISSUE THREAD

**Issue by yohan-kang** [9oormthon2024-T5-SoriSoop/sorisoop-server#12]
### Describe
<주변 조용한 공간 찾기>
1. 프론트에서 전달받은 [위치]들을 기반으로 주변 장소의 평균 데시벨 데이터를 검색
2. 좌표 리스트를 평균 데시벨을 기준으로 오름차순 하여 세번째 인덱스까지 프론트에 좌표 전달
(내 위치를 바탕으로 주변 카페랑 음식점, 문화시설, 관광명소 를 바탕으로 정보를 제공)

### DTO
dto/response/response/NoiseSearchResponse 
```
List<NoiseResponse> noises
List<NoiseReviewResponse> reviews
```

### API 명세 
-  HTTP 메서드: POST
-  Endpoint: POST /api/noise/nearby

Request Body
```
        {
            "x": 127.001,
            "y": 37.001
        }, 
        ...(n개)
```

Response
```
{
  "noises": [
	  {
	    "x": 127.001,
	    "y": 37.001,
	    "averageDecibel": 50,
	    "createdAt": "2024-12-11 14:35"
	  }, 
	  ... (3개 데이터 )
}
```

### Tasks

API 구현
- [x] Service 계층에서 데이터 검증 및 응답 로직 추가 
   (백엔드에서 전달받은 좌표 리스트를 평균 데시벨을 기준으로 오름차순 하여 세번째 인덱스까지 프론트에 좌표 전달)
- [x] Controller 계층에서 요청 처리 및 응답 반환 로직 구현.
- [x] 요청,응답 유효성 검사 (좌표, 평균값, 날짜 값 범위 확인)
- [ ] postman 테스트
