### ISSUE TITLE
[API] 상세 조회

### ISSUE THREAD

**Issue by yohan-kang** [9oormthon2024-T5-SoriSoop/sorisoop-server#13]
### Describe
특정 좌표를 기준으로 Noise 데이터에 대한 상세 정보를 조회

사용자가 데시벨 리스트를 선택하거나 머커를 선택한 경우 해당 장소 좌표 기준으로 반경 50m 이내의 범위 조회 데이터 리스트를 전달 
(최근 한시간 이내의 조건 추가)

### DTO
dto/response/NoiseDetailResponse 
```
int avgDecibel
int maxDecibel
List<NoiseReviewResponse> reviews
```

### API 명세 
-  HTTP 메서드: POST
-  Endpoint: POST /api/noise/detail

Request Body
```
{
	 "x": 127.001,
	 "y": 37.001
}
```

Response
```
{
  "noises": [
    {
      "avgDecibel": 50,
      "createdAt": "2024-12-11T14:35:00"
    },
    {
      "avgDecibel": 60,
      "createdAt": "2024-12-11T14:45:00"
    }
  ],
  "reviews": [
    {
      "userName": "User1",
      "review": "조용하고 좋습니다.",
      "createdAt": "2024-12-11 14:35"
    },
    {
      "userName": "User2",
      "review": "소음이 조금 있습니다.",
      "createdAt": "2024-12-11 14:45"
    }
  ]
}
```

### Tasks

API 구현
- [x] Service 계층에서 데이터 검증 및 응답 로직 추가 
   (백엔드에서 전달받은 좌표를 기준으로 해당 좌표에 리뷰를 등록한 데이터 리스트를 응답)
- [x] Controller 계층에서 요청 처리 및 응답 반환 로직 구현.
- [x] 요청,응답 유효성 검사 (평균 데시벨 ,리뷰, 날짜 확인)
- [ ] postman 테스트 

### ETC

설명에서 특정 좌표만을 기준으로 상세를 보여줘야 하지 않을까? 

최근 한시간 이내의 조건 추가 조건이 필요한가?
