### ISSUE TITLE
[API]마이 페이지- 사용자 Noise 등록 목록 조회

### ISSUE THREAD

**Issue by yohan-kang** [9oormthon2024-T5-SoriSoop/sorisoop-server#16]
### Describe

특정 유저가 등록한 Noise 데이터 리스트를 조회

### DTO
dto/response/response/NoiseSummaryListResponse 
```
List<NoiseSummaryResponse> responses
```

### API 명세 
- **Method**: GET
- **URL**:  /api/user/{userId}

PathVariable
```
long id(유저 고유 식별 ID)
```

Response
```
 {
	"id": 1,
	"x": 127.001,
	"y": 37.001,
	"averageDecibel": 50,
	"maximumDecibel": 70,
	"review": "조용하고 좋습니다.",
	"createdAt": "2024년 12월 11일 14시 35분"
}, 
... (n개 )
```

### Tasks

API 구현
- [x] Service 계층에서 데이터 검증 및 응답 로직 추가 
   (백엔드에서 전달받은 유저 인덱스 정보로 유저 정보 조회 후 데이터 리스트 전달 )
- [x] Controller 계층에서 요청 처리 및 응답 반환 로직 구현.
- [x] 요청,응답 유효성 검사 (좌표, 날짜, 최대평균)
- [ ] postman 테스트
