### ISSUE TITLE
[API]마이페이지->사용자 Noise 등록 목록->상세조회 

### ISSUE THREAD

**Issue by yohan-kang** [9oormthon2024-T5-SoriSoop/sorisoop-server#17]
### Describe

유저가 등록한 특정 Noise 데이터의 상세 정보를 조회

### DTO
dto/response/response/NoiseSummaryResponse 
```
Long id
double x
double y
int measurementTime
int averageDecibel
int maximumDecibel
String createdAt
```

### API 명세 
- **Method**: GET
- **URL**: /api/user/noise/{noiseId}

PathVariable
```
long id(노이즈 고유 식별 ID)
```

Response
```
{
    "id": 1,
    "x": 127.001,
    "y": 37.001,
    "averageDecibel": 50,
    "maximumDecibel": 70,
    "review": "조용하고 좋습니다.",
    "createdAt": "2024년 12월 11일 14시 35분"
},
```

### Tasks

API 구현
- [x] Service 계층에서 데이터 검증 및 응답 로직 추가 
   ( 프론트에서 전달받은 데이터 인덱스값으로 데이터 추출)
- [ ] Controller 계층에서 요청 처리 및 응답 반환 로직 구현.
- [ ] 요청,응답 유효성 검사 (데이터 Idx, 좌표, 날짜, 최대, 평균, 한줄평 확인)
- [ ] postman 테스트
