### ISSUE TITLE
[API] 노이즈 데이터 삭제

### ISSUE THREAD

**Issue by yohan-kang** [9oormthon2024-T5-SoriSoop/sorisoop-server#18]
### Describe
특정 Noise 데이터를 삭제

### DTO
```
```

### API 명세 
- **Method**: DELETE
- **URL**: /api/noise/{id}
	•	Path Variable:
	•	id: 삭제할 Noise 데이터의 고유 ID (Long)

Request
```
Path Variable:
id: 삭제할 Noise 데이터의 고유 ID (Long)
```

Response
```
HTTP 상태 코드
	•	200 OK: 데이터 삭제 성공.
	•	404 Not Found: 삭제할 데이터가 존재하지 않을 경우.
```

### Tasks

API 구현
- [ ] Service 계층에서 NoiseService에 ID로 데이터 삭제 로직 구현.삭제 대상이 없을 경우 예외 처리 추가.
- [ ] 	Controller 계층에서 삭제 요청을 처리하는 DELETE /api/noise/{id} 메서드 구현.
- [ ] 요청,응답 유효성 검사 (데이터 정상 삭제 확인)
- [ ] postman 테스트
