### ISSUE TITLE
엔티티 ID 설정 변경

### ISSUE THREAD

**Issue by minjo-on** [9oormthon2024-T5-SoriSoop/sorisoop-server#36]
### Describe

엔티티마다 id 필드와 extractUuid() 메서드를 중복 정의하고 있어 유지보수성과 코드의 중복 문제가 발생하고 있습니다. 이를 해결하기 위해 BaseTimeEntity로 id 필드를 이동하고, 공통 메서드인 extractUuid()도 BaseTimeEntity에서 정의하여 중복 구현을 제거하려고 합니다. 이렇게 하면 각 엔티티는 공통 상속 구조를 활용하여 일관성을 유지할 수 있습니다.

### Tasks

- [ ] 1.  id 필드를 BaseTimeEntity로 이동.

- [x] 2. @Id와 @PrefixedUuid 어노테이션 적용.
    - 공통 메서드 extractUuid()를 BaseTimeEntity에 정의.
    - 엔티티에서 중복 코드 제거

- [x] 3. 각 엔티티에서 개별적으로 정의된 id 필드와 extractUuid() 메서드 제거.
    - BaseTimeEntity 상속 구조로 통합.
    - Hibernate ID Generator 재확인

- [x] 4. PrefixedUuidGenerator가 각 엔티티에서 적절히 작동하는지 테스트.
    - Prefix 설정이 올바르게 적용되었는지 확인.

### ETC

이 작업으로 id 필드의 관리가 중앙화되어 일관성이 향상될 것으로 기대합니다.
