### ISSUE TITLE
dependabot 적용

### ISSUE THREAD

**Issue by minjo-on** [9oormthon2024-T5-SoriSoop/sorisoop-server#38]
### Describe

Dependabot을 적용하여 프로젝트의 의존성 업데이트를 자동화하고 보안 취약점과 최신 버전 관리 효율성을 높입니다.

### Tasks

- [x] .github/dependabot.yml 파일 생성.
- [x] 의존성 관리 대상 명시.
- [x] 업데이트 주기(예: daily, weekly) 설정.
