### ISSUE TITLE
AOP와 인터셉터를 이용해 로깅 적용

### ISSUE THREAD

**Issue by minjo-on** [9oormthon2024-T5-SoriSoop/sorisoop-server#47]
### Describe

AOP와 인터셉터를 활용하여 로깅 시스템을 구현합니다. 이 로깅 시스템은 주요 비즈니스 로직의 실행 시간, API 요청 및 응답 데이터, 예외 상황 등을 기록하여 디버깅과 운영 모니터링에 도움을 줄 수 있도록 설계됩니다. 이를 통해 시스템 상태를 효과적으로 추적하고, 잠재적 문제를 조기에 감지할 수 있도록 지원합니다.

### Tasks

- [ ] 1. **API 실행마다 로그 출력되도록 Pointcut 설정**
   - Pointcut 설정 시, Controller 혹은 Service 계층에 대해 필터링 적용.
   - 로그에 포함될 기본 정보(메서드명, 매개변수, 반환값 등) 정의.

- [ ] 2. **500 서버 에러에 대한 세부 로그 출력**
   - 발생한 에러의 원인과 API Endpoint를 명확히 기록.

- [ ] 3. **API 실행 시간 출력**
   - 실행 시간 로깅을 AOP를 통해 측정 및 기록.
   - 일정 시간 초과 시 경고 로그로 레벨 조정(INFO → WARN).
