### ISSUE TITLE
CICD 설정

### ISSUE THREAD

**Issue by minjo-on** [9oormthon2024-T5-SoriSoop/sorisoop-server#50]
### Describe

 CICD(Continuous Integration and Continuous Deployment) 파이프라인을 구축하여 자동화된 코드 배포와 테스트 환경을 설정합니다. 이를 통해 코드 변경 사항을 신속하고 안정적으로 배포하고, 팀의 개발 효율성을 극대화합니다.

#### Tasks  

- [ ] 1. **GitHub Actions 설정**  
   - `.github/workflows` 디렉터리에 CICD 설정 파일 생성.  
   - 코드 빌드, 테스트, 배포를 포함한 워크플로우 작성.  

- [ ] 2. **빌드 및 테스트 자동화**   
   - Gradle을 사용한 프로젝트 빌드 및 테스트 단계 구성.  
   - 실패 시 알림을 받을 수 있도록 설정.  

- [ ] 3. **Docker 배포 설정**  
   - Dockerfile 작성 및 Docker 이미지를 빌드하여 배포 가능하도록 구성.  
   - Docker Hub 또는 내부 레지스트리에 이미지 업로드 설정.  

- [ ] 4. **서버 배포 자동화**  
   - AWS 클라우드 서비스를 활용한 배포 스크립트 작성.  
   - SSH 및 환경 변수 설정 관리.
